-- stylua: ignore start
require "user.launch"
require "user.options"
require "user.keymaps"
require "user.autocmds"

spec "plugins.snacks"

spec "plugins.adr-tools"
spec "plugins.autopairs"
-- spec "plugins.breadcrumbs"
-- spec "plugins.cellular-automaton"
spec "plugins.blink"
-- spec "plugins.cmp"
-- spec "plugins.colorizer"
spec "plugins.colorscheme"
spec "plugins.comment"
spec "plugins.conform"
-- spec "plugins.copilot"
spec "plugins.devicons"
spec "plugins.eyeliner"
spec "plugins.gitlab"
spec "plugins.gitsigns"
-- spec "plugins.harpoon" try alternatives
spec "plugins.illuminate"
spec "plugins.lspconfig"
spec "plugins.lualine"
spec "plugins.luasnip"
spec "plugins.mason"
-- spec "plugins.miniicons"
-- spec "plugins.navbuddy"
spec "plugins.navic"
-- spec "plugins.neogit"
spec "plugins.neotest"
spec "plugins.none-ls"
spec "plugins.obsidian"
spec "plugins.oil"
spec "plugins.schemastore"
spec "plugins.smart-splits"
spec "plugins.todo-comments"
spec "plugins.treesitter"
spec "plugins.typst"
spec "plugins.trouble"
-- spec "plugins.ufo"
spec "plugins.vim-helm"
spec "plugins.whichkey"
spec "plugins.wrapping"

require "user.lazy"
-- stylua: ignore end
